[package]
name = "makepass"
version = "1.0.0"
authors = ["Nathan West <Lucretiel@gmail.com>"]
edition = "2021"

[dependencies]
structopt = "0.2"
rand = "0.8.4"
clap= "2.34"
atty = "0.2.11"
thiserror = "1.0.20"
lazy_format = "2.0.0"

[build-dependencies]
joinery = "3.1.0"
lazy_format = "2.0.0"
